### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [8]:
#Declare the function
def BetIndexes(chaine,a,b):
    L = chaine[a:b+1]
    return(L,len(L))

#Call the function
chaine = 'abcdef'
a = 1
b = 3
BetIndexes(chaine,a,b)

#print the result in a well formated format
smallchaine = BetIndexes(chaine,a,b)[0]
Taille = BetIndexes(chaine,a,b)[1]
print('Slice of the string between the indexes',a,'and',b,':',smallchaine)
print('Lenght of the slice :',Taille)

Slice of the string between the indexes 1 and 3 : bcd
Lenght of the slice : 3


### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [67]:
#Declare the function
def somme(a,b):
    return(a+b)

#Call with the values 1 and two
S1 = somme(1,2)
type(S1)

#Check the type of the result
S2 = somme(False,2)
print(S2)
type(S2)

2


int

### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [19]:
#Declare the function
def CharFrequency(chaine):
    d = {}
    for i in chaine:
        d[i] = chaine.count(i)
    return(d)

#Print the result
chaine = 'test'
cf = CharFrequency(chaine)
print(cf)

{'t': 2, 'e': 1, 's': 1}


### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [23]:
x=[1,2,3]
y=[1,2,3]
for i in range(len(x)):
    print(x[i],y[-i-1])

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [50]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)

#Try to print input
print(a)
print(b)

#concatenate horizontally
C = np.concatenate((a[0], b[0]))
D = np.concatenate((a[1],b[1]))
L = np.concatenate((C,D)).reshape(2,-1)
print(L)

#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])





[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [58]:
import numpy as np
a = np.arange(3)
b = np.ones((3,3,3))

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
c = np.repeat(a,3)
d = np.tile(a,3)
e = np.concatenate((c,d))
print(e)

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])
f = b * (a+1)
print(f)

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
g = b.reshape((3,9))
print(g)

[0 0 0 1 1 1 2 2 2 0 1 2 0 1 2 0 1 2]
[[[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 3.]
  [1. 2. 3.]
  [1. 2. 3.]]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
